version: '3.8'

services:
  backend:
    build:
      context: ./rest_api
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    depends_on:
      - mongodb
      - mqtt
    hostname: backend

  frontend:
    build:
      context: ./dashboard
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ./.env
    hostname: frontend

  mongodb:
    build:
      context: ./mongodb
    container_name: mongodb
    ports:
      - "27017:27017"
    env_file:
      - ./.env
    hostname: mongodb


  mqtt:
    build:
      context: ./mosquitto
    container_name: mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    hostname: mqtt


  simulation-test:
    build:
      context: ./simulation-test
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - backend
    hostname: simulation-test