services:
  - name: backend
    type: web
    env: docker
    dockerfilePath: ./rest_api/Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - file: ./.env
    plan: free

  - name: frontend
    type: web
    env: docker
    dockerfilePath: ./dashboard/Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - file: ./.env
    plan: free

  - name: mongodb
    type: private
    env: docker
    image: mongo:5.0
    startCommand: ""
    envVars:
      - file: ./.env
    plan: free
    volumes:
      - mountPath: /docker-entrypoint-initdb.d
        source: ./mongodb/mongo-init.js
        type: bind

  - name: mqtt
    type: private
    env: docker
    image: eclipse-mosquitto:2.0
    startCommand: mosquitto -c /mosquitto/mosquitto.conf
    envVars:
      - file: ./.env
    plan: free
    volumes:
      - mountPath: /mosquitto/passwd
        source: ./mosquitto/passwd
        type: bind
      - mountPath: /mosquitto/data
        source: ./mosquitto/data
        type: bind
      - mountPath: /mosquitto/log
        source: ./mosquitto/log
        type: bind
      - mountPath: /mosquitto/mosquitto.conf
        source: ./mosquitto/mosquitto.conf
        type: bind

  - name: simulation-test
    type: web
    env: docker
    dockerfilePath: ./simulation-test/Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - file: ./.env
    plan: free
