version: '3.8'
services:
  app:
    image: restapi:latest  # Use a specific Bun image or build one as needed
    build:
      context: .  # Path to your Dockerfile
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Map Bun app's port to host (change as per your app)
    env_file:
      - .env
