FROM oven/bun:alpine

WORKDIR /app

# Copy all source code and package
COPY . .

# Install dependencies
RUN bun install  

# Expose the port on which the app will run
EXPOSE 8080

# Start the application
CMD ["bun", "index.ts"]
