export const NEXT_PUBLIC_MQTTWEBSOCKET = process.env.NEXT_PUBLIC_MQTTWEBSOCKET;
export const NEXT_PUBLIC_MQTT_USERNAME = process.env.NEXT_PUBLIC_MQTT_USERNAME;
export const NEXT_PUBLIC_MQTT_PASSWORD = process.env.NEXT_PUBLIC_MQTT_PASSWORD;